#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 YOUR NAME HERE.  All Rights Reserved.
#
# FS QA Test 601
#
# what am I here for?
# Test for panic during ioerror reading xattr blocks
#
. ./common/preamble
_begin_fstest auto

# Override the default cleanup function.
_cleanup()
{
	cd /
	rm -f $tmp.*
	_dmerror_cleanup
}

# Import common functions.
# . ./common/filter
. ./common/dmerror

# real QA test starts here

# Modify as appropriate.
_supported_fs xfs
_require_scratch
_require_dm_target error

_scratch_mkfs >> $seqres.full
_scratch_mount

# Originally I thought the problem I was chasing was  triggered by reading an
# extent based attribute fork on an existing file.  But that turns out not to
# be the case. 

echo "Create extributes to push the attribute fork out of the inode" >> $seqres.full

# For this to be general the length to fail should be based off the size of the
# attribute fork. For simplicity just create a value large enough to push it out
# of the inode.
touch $SCRATCH_MNT/testfile

# Push out of inode
setfattr -n user.test -v $(printf "teatdata_out_of_inode:%0.512d" 1) $SCRATCH_MNT/testfile
# Push second leaf
setfattr -n user.test -v $(printf "teatdata_out_of_leaf1:%0.4096d" 1) $SCRATCH_MNT/testfile
setfattr -n user.test -v $(printf "teatdata_out_of_leaf2:%0.8192d" 1) $SCRATCH_MNT/testfile

attrblocks=($($XFS_IO_PROG -c "bmap -al" $SCRATCH_MNT/testfile | awk 'match($3, /[0-9]+/, a) {print a[0]}'))
echo attribute fork at blocks ${attrblocks[*]} >> $seqres.full

# todo use drop_caches instead of unmount.
_scratch_unmount

_dmerror_init >> $seqres.full 2>&1
_dmerror_reset_table
_dmerror_mount >> $seqres.full 2>&1

echo "Setup to error when reading the attrtribute second attribute block ${attrblocks[1]}" >> $seqres.full
_dmerror_mark_range_bad ${attrblocks[1]} 1 $SCRATCH_DEV

# debug from 556
cat >> $seqres.full << ENDL
dmerror after marking bad:
$DMERROR_TABLE
$DMERROR_RTTABLE
<end table>
ENDL

_dmerror_load_error_table

# Panic here if failure
echo "Reread the extended attribute, panics on unandled ioerrors" >> $seqres.full
getfattr -d - $SCRATCH_MNT/testfile

# if error
exit

# optional stuff if your test has verbose output to help resolve problems
#echo
#echo "If failure, check $seqres.full (this) and $seqres.full.ok (reference)"

# success, all done
status=0
exit
